### ISSUE TITLE
module 'tensorflow.contrib.estimator' has no attribute 'stop_if_no_decrease_hook'

### ISSUE THREAD

**Issue by bxccc** [macanv/BERT-BiLSTM-CRF-NER#181]
module 'tensorflow.contrib.estimator' has no attribute 'stop_if_no_decrease_hook'
tensorflow版本1.14.0

**Comment by Beaujor** [comment]
我也是tensorflow版本1.14.0，也遇到了同样的问题，请问您是怎么解决的？

**Comment by bxccc** [comment]
是tensorflow版本问题 我换成了1.13版本的 1.12应该也是可以的------------------ 原始邮件 ------------------
发件人: "Beaujor"<notifications@github.com>
发送时间: 2019年7月13日(星期六) 晚上10:11
收件人: "macanv/BERT-BiLSTM-CRF-NER"<BERT-BiLSTM-CRF-NER@noreply.github.com>;
抄送: "bxccc"<2933908002@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [macanv/BERT-BiLSTM-CRF-NER] module'tensorflow.contrib.estimator' has no attribute 'stop_if_no_decrease_hook'(#181)



我也是tensorflow版本1.14.0，也遇到了同样的问题，请问您是怎么解决的？
 
&mdash;

**Comment by Beaujor** [comment]
非常感谢╰(*´︶`*)╯发自我的华为手机-------- 原始邮件 --------主题：Re: [macanv/BERT-BiLSTM-CRF-NER] module 'tensorflow.contrib.estimator' has no attribute 'stop_if_no_decrease_hook' (#181)发件人：bxccc 收件人：macanv/BERT-BiLSTM-CRF-NER 抄送：Beaujor ,Comment 是tensorflow版本问题 我换成了1.13版本的 1.12应该也是可以的------------------ 原始邮件 ------------------



发件人: "Beaujor"<notifications@github.com>



发送时间: 2019年7月13日(星期六) 晚上10:11



收件人: "macanv/BERT-BiLSTM-CRF-NER"<BERT-BiLSTM-CRF-NER@noreply.github.com>;



抄送: "bxccc"<2933908002@qq.com>;"State change"<state_change@noreply.github.com>;



主题: Re: [macanv/BERT-BiLSTM-CRF-NER] module'tensorflow.contrib.estimator' has no attribute 'stop_if_no_decrease_hook'(#181)















我也是tensorflow版本1.14.0，也遇到了同样的问题，请问您是怎么解决的？



 



&mdash;



You are receiving this because you modified the open/close state.



Reply to this email directly, view it on GitHub, or mute the thread.



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/macanv/BERT-BiLSTM-CRF-NER/issues/181?email_source=notifications\u0026email_token=ABPZQBNLFRXABZMD3LFEGETP7HPRHA5CNFSM4IB63SL2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZ3SPCQ#issuecomment-511125386",

"url": "https://github.com/macanv/BERT-BiLSTM-CRF-NER/issues/181?email_source=notifications\u0026email_token=ABPZQBNLFRXABZMD3LFEGETP7HPRHA5CNFSM4IB63SL2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZ3SPCQ#issuecomment-511125386",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by sandeeppilania** [comment]
@bxccc @Beaujor 
您曾使用过哪种版本？

**Comment by Beaujor** [comment]
1.12发自我的华为手机-------- 原始邮件 --------主题：Re: [macanv/BERT-BiLSTM-CRF-NER] module 'tensorflow.contrib.estimator' has no attribute 'stop_if_no_decrease_hook' (#181)发件人：sandeeppilania 收件人：macanv/BERT-BiLSTM-CRF-NER 抄送：Beaujor ,Mention @bxccc @Beaujor

您曾使用过哪种版本？



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/macanv/BERT-BiLSTM-CRF-NER/issues/181?email_source=notifications\u0026email_token=ABPZQBOUXQ6PQ4CP7EKDSCLP76L77A5CNFSM4IB63SL2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2GYMVI#issuecomment-512591445",

"url": "https://github.com/macanv/BERT-BiLSTM-CRF-NER/issues/181?email_source=notifications\u0026email_token=ABPZQBOUXQ6PQ4CP7EKDSCLP76L77A5CNFSM4IB63SL2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2GYMVI#issuecomment-512591445",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Beaujor** [comment]
1.12，1.14会出这个问题。发自我的华为手机-------- 原始邮件 --------主题：Re: [macanv/BERT-BiLSTM-CRF-NER] module 'tensorflow.contrib.estimator' has no attribute 'stop_if_no_decrease_hook' (#181)发件人：sandeeppilania 收件人：macanv/BERT-BiLSTM-CRF-NER 抄送：Beaujor ,Mention @bxccc @Beaujor

您曾使用过哪种版本？



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/macanv/BERT-BiLSTM-CRF-NER/issues/181?email_source=notifications\u0026email_token=ABPZQBOUXQ6PQ4CP7EKDSCLP76L77A5CNFSM4IB63SL2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2GYMVI#issuecomment-512591445",

"url": "https://github.com/macanv/BERT-BiLSTM-CRF-NER/issues/181?email_source=notifications\u0026email_token=ABPZQBOUXQ6PQ4CP7EKDSCLP76L77A5CNFSM4IB63SL2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2GYMVI#issuecomment-512591445",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by BlasTJSN** [comment]
> 我也是tensorflow版本1.14.0，也遇到了同样的问题，请问您是怎么解决的？

确实是新版本问题，1.14.0版本通过import tensorflow.estimator.experimental.stop_if_no_decrease_hook进行调用. 
具体变化参考：https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/compatibility/all_renames_v2.py

**Comment by Beaujor** [comment]
换成1.12或1.13，前者我试过可以。发自我的华为手机-------- 原始邮件 --------主题：Re: [macanv/BERT-BiLSTM-CRF-NER] module 'tensorflow.contrib.estimator' has no attribute 'stop_if_no_decrease_hook' (#181)发件人：JIN 收件人：macanv/BERT-BiLSTM-CRF-NER 抄送：Beaujor ,Mention 

我也是tensorflow版本1.14.0，也遇到了同样的问题，请问您是怎么解决的？



确实是新版本问题，1.14.0版本通过import tensorflow.estimator.experimental.stop_if_no_decrease_hook进行调用.

具体变化参考：https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/compatibility/all_renames_v2.py



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/macanv/BERT-BiLSTM-CRF-NER/issues/181?email_source=notifications\u0026email_token=ABPZQBKNI5IBB3IOFG4P2RLQBANPDA5CNFSM4IB63SL2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2VXKTI#issuecomment-514553165",

"url": "https://github.com/macanv/BERT-BiLSTM-CRF-NER/issues/181?email_source=notifications\u0026email_token=ABPZQBKNI5IBB3IOFG4P2RLQBANPDA5CNFSM4IB63SL2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2VXKTI#issuecomment-514553165",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
