### ISSUE TITLE
关于英文CoNLL2003 报训练集太小？何种方式验证数据集上的指标？

### ISSUE THREAD

**Issue by Nicozwy** [macanv/BERT-BiLSTM-CRF-NER#206]
使用以下方式运行：
> bert-base-ner-train \
>     -data_dir {your dataset dir}\
>     -output_dir {training output dir}\
>     -init_checkpoint {Google BERT model dir}\
>     -bert_config_file {bert_config.json under the Google BERT model dir} \
>     -vocab_file {vocab.txt under the Google BERT model dir}
### 报错
> File "D:\projects\BERT-BiLSTM-CRF-NER\bert_base\train\bert_lstm_ner.py", line 570, in train
raise AttributeError('training data is so small...')
###换成 
python run.py的方式运行，会产生Exhausted resource。

想请问下，如果我想验证该代码 数据集上的准确率和F1值，应该以何种方式运行？？

**Comment by 393301836** [comment]
2019-08-01 21:06:38.087488: W tensorflow/compiler/xla/service/platform_util.cc:240] unable to create StreamExecutor for CUDA:0: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: **out of memory**; total memory reported: 11522867200
2019-08-01 21:06:38.089459: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: no supported devices found for platform CUDA
Aborted **(core dumped)**

**Comment by macanv** [comment]
OOM 问题已经有很多人提问了，自己搜一下吧

英文数据集，需要修改输入。

**Comment by macanv** [comment]
https://github.com/macanv/BERT-BiLSTM-CRF-NER/blob/master/bert_base/train/bert_lstm_ner.py
56行的函数。

**Comment by liuchao80000** [comment]
楼主你好，conll2003的修改代码可否看一下？

**Comment by lidejian** [comment]
@zwacm @liuchao80000 应该是修改  macanv 说的那个文件下的第139行那个函数，把第148行修改为：if len(tokens) == 2 or len(tokens) == 4: 即可。因为conll 2003的数据集是4列。而非两列

**Comment by huanghonggit** [comment]
您好，如果是英文数据集，如果调用分词后一个单词被分为几个子词，为什么第一个label是 比如 B-drug，而后面的几个子词的label却是X?

`    for i, word in enumerate(textlist):
        # 分词，如果是中文，就是分字,但是对于一些不在BERT的vocab.txt中得字符会被进行WordPice处理（例如中文的引号），可以将所有的分字操作替换为list(input)
        token = tokenizer.tokenize(word)
        tokens.extend(token)
        label_1 = labellist[i]
        for m in range(len(token)):
            if m == 0:
                labels.append(label_1)
            else:  # 一般不会出现else
                labels.append("X")`

这部分代码需要怎样修改勒，能不能请您指点怎么修改，bert的源码没有涉及label？
